name: Build React App and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        env:
          CI: false

      - name: Build React App
        run: npm run build

      - name: Upload Build as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build/
      - name: Trigger backend deployment
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/jumpei-yamamoto/SmartSpezTech/dispatches \
          -d '{"event_type":"deploy_backend"}'
