name: Build Docker Image and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-3
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com
      ECR_REPOSITORY: smartspeztech
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # .elasticbeanstalkフォルダを削除
      - name: Remove Elastic Beanstalk config
        run: |
          rm -rf .elasticbeanstalk/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # AWS認証情報の設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-3

      # Amazon ECRにログイン (リージョンを指定)
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # DockerイメージのビルドとECRへのプッシュ
      - name: Build and push Docker image to ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Elastic Beanstalk CLIのインストール
      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      # Elastic Beanstalkへのデプロイ
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker smartspeztech --region ap-northeast-3
          eb use smartspeztech
          eb deploy
