name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        env:
          CI: false

      - name: Build React App
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-3

      - name: Sync S3
        run: aws s3 sync build/ s3://smartspeztech --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EMGJTZ0KGVFPH --paths "/*"
